# Generated by Django 2.2.2 on 2019-07-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomautor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeditorial', models.CharField(max_length=100)),
                ('ciueditorial', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estejemplar', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Ejemplares',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nompais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomusuario', models.CharField(max_length=100)),
                ('tipousuario', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecprestamo', models.DateField(auto_now_add=True)),
                ('fecdevolucion', models.DateField(auto_now_add=True)),
                ('fecentrega', models.DateField(auto_now_add=True)),
                ('ejemplares_codejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_prestamos2', to='sistema.Ejemplar')),
                ('usuarios_codusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_prestamos1', to='sistema.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=6)),
                ('estado', models.CharField(max_length=2)),
                ('detalle', models.CharField(max_length=100)),
                ('prestamos_ejemplares_codejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_multas1', to='sistema.Prestamo')),
                ('prestamos_fecprestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_multas3', to='sistema.Prestamo')),
                ('prestamos_usuarios_codusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_multas2', to='sistema.Prestamo')),
            ],
            options={
                'verbose_name_plural': 'Multas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomlibro', models.CharField(max_length=100)),
                ('autores_codautor', models.ManyToManyField(to='sistema.Autor')),
                ('editoriales_codeditorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_libros', to='sistema.Editorial')),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libros_codlibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_ejemplares', to='sistema.Libro'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='paises_codpais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_editoriales', to='sistema.Pais'),
        ),
        migrations.AddField(
            model_name='autor',
            name='paises_codpais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_autores', to='sistema.Pais'),
        ),
    ]
