# Generated by Django 2.2.3 on 2019-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.BigIntegerField(),
        ),
    ]
