# Generated by Django 2.2.3 on 2019-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190717_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
